import { Router } from "express";
import { prisma } from "../lib/prisma.js";
import { requireAdmin } from "../lib/adminAuth.js";
import { deleteObject, keyFromPublicUrl } from "../lib/s3.js";

const router = Router();

router.use(requireAdmin);

// Prisma's per-query `omit` isn't available on the client generated by this
// project's Prisma version, so evidenceToken is stripped manually here
// instead — it must never reach any admin (or public) response body.
function omitToken(report) {
  const { evidenceToken, ...rest } = report;
  return rest;
}

// GET /api/admin/reports/pending — reports with evidence awaiting approval
router.get("/reports/pending", async (req, res, next) => {
  try {
    const reports = await prisma.report.findMany({
      where: { approved: false },
      include: { evidence: true, replies: true },
      orderBy: { createdAt: "asc" },
    });
    res.json({ reports: reports.map(omitToken) });
  } catch (err) {
    next(err);
  }
});

// POST /api/admin/reports/:id/approve
router.post("/reports/:id/approve", async (req, res, next) => {
  try {
    const report = await prisma.report.update({
      where: { id: req.params.id },
      data: { approved: true },
    });
    res.json(omitToken(report));
  } catch (err) {
    if (err.code === "P2025") return res.status(404).json({ error: "Report not found" });
    next(err);
  }
});

// GET /api/admin/flagged — auto-hidden or flagged reports & replies needing review
router.get("/flagged", async (req, res, next) => {
  try {
    const [reports, replies] = await Promise.all([
      prisma.report.findMany({
        where: { OR: [{ hidden: true }, { flagCount: { gt: 0 } }] },
        include: { evidence: true },
        orderBy: { flagCount: "desc" },
      }),
      prisma.reply.findMany({
        where: { OR: [{ hidden: true }, { flagCount: { gt: 0 } }] },
        orderBy: { flagCount: "desc" },
      }),
    ]);
    res.json({ reports: reports.map(omitToken), replies });
  } catch (err) {
    next(err);
  }
});

// POST /api/admin/reports/:id/unhide
router.post("/reports/:id/unhide", async (req, res, next) => {
  try {
    const report = await prisma.report.update({
      where: { id: req.params.id },
      data: { hidden: false, flagCount: 0 },
    });
    res.json(omitToken(report));
  } catch (err) {
    if (err.code === "P2025") return res.status(404).json({ error: "Report not found" });
    next(err);
  }
});

// DELETE /api/admin/reports/:id — permanent removal, including S3 evidence objects
router.delete("/reports/:id", async (req, res, next) => {
  try {
    const report = await prisma.report.findUnique({
      where: { id: req.params.id },
      include: { evidence: true },
    });
    if (!report) return res.status(404).json({ error: "Report not found" });

    await Promise.all(
      report.evidence.map(async (e) => {
        const key = keyFromPublicUrl(e.fileUrl);
        if (key) await deleteObject(key).catch((err) => console.warn(`[admin] failed to delete S3 object ${key}: ${err.message}`));
      })
    );

    await prisma.report.delete({ where: { id: report.id } }); // cascades to evidence + replies

    res.status(204).end();
  } catch (err) {
    next(err);
  }
});

// POST /api/admin/replies/:id/unhide
router.post("/replies/:id/unhide", async (req, res, next) => {
  try {
    const reply = await prisma.reply.update({
      where: { id: req.params.id },
      data: { hidden: false, flagCount: 0 },
    });
    res.json(reply);
  } catch (err) {
    if (err.code === "P2025") return res.status(404).json({ error: "Reply not found" });
    next(err);
  }
});

// DELETE /api/admin/replies/:id — permanent removal
router.delete("/replies/:id", async (req, res, next) => {
  try {
    await prisma.reply.delete({ where: { id: req.params.id } });
    res.status(204).end();
  } catch (err) {
    if (err.code === "P2025") return res.status(404).json({ error: "Reply not found" });
    next(err);
  }
});

export default router;
